# Basic
title: Perfectroot
subtitle: To change later
welcome_message: insert flag
# description: Vno Jekyll is a port of my Ghost theme vno.
creator: perfectroot

# url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green
# The blog button should not be removed.
blog_button:
    title: CTF writeups
    description: Our Writeups

about_button:
    title: about
    description: about

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: Team members blogs }
    - {title: About Us, description: About, url: _about}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
# comment:
#     disqus: p3rf3ctr00t
    # duoshuo: 
    
# Social
social:
    #weibo: onevcat
    github: p3rf3ctr00t
    twitter: p3rf3ctr00t
    #gplus: 107108267983477358170
    mail: p3rf3ctr00t001@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
